### ISSUE TITLE
Regex with | symbol

### ISSUE THREAD

**Issue by IgorNoskov** [rakit/validation#103]
I tried this expression: `required|regex:/^\d$|^(?:\d+\,?)+\d+$/`, and catch the error with message "Uncaught exception: 'Rakit\Validation\RuleNotFoundException" with message 'Validator '^(?' is not registered". The symbol | don't work in an expression.

**Comment by YaseenTwati** [comment]
having the same problem

**Comment by YaseenTwati** [comment]
@IgorNoskov after doing a bit of search in the old issues 
it seems like one way of solving it is using the array syntax

take a look at #78 
``'something'      => ['required', 'regex:/some_regex/'] ...

**Comment by IgorNoskov** [comment]
@YaseenTwati thank you!

**Comment by EduVillas** [comment]
Same problem with select input with only 2 options required: a OR i 
'var' => 'regex: /[a|i]/'
