### ISSUE TITLE
Questions about the uploaded file rule

### ISSUE THREAD

**Issue by adelowo** [rakit/validation#11]
Hi @emsifa , 

- Why are you checking if a file is valid by just the array keys ? https://github.com/rakit/validation/blob/master/src/Rules/UploadedFile.php#L105-#L114 . You could resort to [`is_uploaded_file`](http://php.net/manual/en/function.is-uploaded-file.php). This seems very much safer than the current implementation available.

Plus there seem to be a bug here 😀 https://github.com/rakit/validation/blob/master/src/Validator.php#L26-#L28

**Comment by emsifa** [comment]
I don't know how to test `is_uploaded_file`. If you know it, it is good to put it in.

Ups, my mistake there. I'll fix that. Thanks for report.

**Comment by adelowo** [comment]
Would send a pull request for this later on

**Comment by emsifa** [comment]
@adelowo I'll wait for it. Thanks before

For bug `setMessages` I already fix it here #12 :smiley:

**Comment by adelowo** [comment]
OK, I've tried to do this but I was unsuccessful.. The main reason is because I couldn't override the function call since the tests are not under a namespace..  I wanted to use the namespace trick. 

https://secure.php.net/manual/en/language.namespaces.fallback.php

https://secure.php.net/manual/en/language.namespaces.faq.php

**Comment by emsifa** [comment]
How does your namespace trick works?

I just read this article http://blog.pixelastic.com/2010/08/04/testing-file-uploads-in-php/

Maybe we can add new static method in `UploadedFileRule` class that just returning `is_uploaded_file`. Then for tests we override that method in new class, and update default validator using `setValidator`.

**Comment by adelowo** [comment]
The namespace trick - -  it's all about redefining the function in a namespace file -  in this case, the test file. The redeclared function would then override the real function from php whenever that test is executed... 

But anyways, I don't really like the approach you linked to.. Another viable option is to mock that method.. I would send a PR that does just that..

**Comment by adelowo** [comment]
The namespace trick - -  it's all about redefining the function in a namespace file -  in this case, the test file. The redeclared function would then override the real function from php whenever that test is executed... 

But anyways, I don't really like the approach you linked to.. Another viable option is to mock that method.. I would send a PR that does just that..

**Comment by adelowo** [comment]
But that might take some time as I'd be quite busy for some time...

**Comment by emsifa** [comment]
I think your namespaced trick is better than override/mock a new method. You can try it first, I will wait for it :smiley:

**Comment by adelowo** [comment]
That can't be used as the tests are in the global scope... Would lead to an error like : can't redeclare `function ` in Foo.php line x

**Comment by emsifa** [comment]
Merged. Will add new release for this.
