### ISSUE TITLE
Boolean validation

### ISSUE THREAD

**Issue by saila-nasrin** [rakit/validation#113]
Can't find any validator for boolean. Is it supported in this library or need custom implementation?

**Comment by devhammed** [comment]
You can use the callback rule to check for boolean values. I once used below, you can tweak it to your needs:

```php
$validator = new Validator();
$validation = $validator->validate($_POST, [
  'accept_terms' => [
    'required',
    function ($value) {
      return in_array($value, [true, false, 'true', 'false', '0', '1', 'y', 'n']);
    },
  ]
]);
```

PS: Stolen from Laravel's boolean validation rule: https://laravel.com/docs/5.8/validation#rule-boolean

**Comment by zabjd22** [comment]
This should be included in the Core Rules.

**Comment by devhammed** [comment]
@theZetrax I have just opened a pull request [here](https://github.com/rakit/validation/pull/126), hopefully it would be merged ASAP.
