### ISSUE TITLE
Minimum value

### ISSUE THREAD

**Issue by agsachdev** [rakit/validation#116]
How to check minimum value?
like minimum 0.01

**Comment by emsifa** [comment]
Sorry for late reply.

You can do something like this:

```php
<?php

$validator = new Rakit\Validation\Validator();
$validation = $validator->validate([
    'number' => '0.01'
], [
    'number' => 'numeric|min:0.01'
]);

$passes = $validation->passes(); // this should be true
```

In example above `numeric` rule is needed to treat numeric string size to its numeric value.
