### ISSUE TITLE
Help: How to use date validation

### ISSUE THREAD

**Issue by dhonx** [rakit/validation#124]
I don't know how to use `date` validation. I need help ... I hope documentation about this is available

**Comment by dhonx** [comment]
Can you help me...?
CC: @emsifa

**Comment by emsifa** [comment]
Hello @dhonx , you can use `date` rule, you can find it in the documentation in [Available Rules section](https://github.com/rakit/validation#available-rules).

This is the example:

```php
$validation = $validator->validate($inputs, [
    "due_date" => "date" // use "date:m/d/Y" to allows "02/17/2020"
]);
```

If you want to specify minimum or maximum date, you can use `after` or `before` rule.

**Comment by dhonx** [comment]
Thanks, @emsifa !!

**Comment by dhonx** [comment]
BTW @emsifa I see the documentation. What I mean is the example

**Comment by kolumb** [comment]
@dhonx Maybe like this?
```php
$validation = $validator->validate([
    'title' => 'Lorem Ipsum',
    'body' => 'Lorem ipsum dolor sit amet ...',
    'receiptdate' => null,
    'graduationdate' => null,
], [
    'title' => 'required',
    'body' => 'required',
    'receiptdate' => 'required|date|format:Y-m-d',
    'graduationdate' => 'date'
]);```

**Comment by uacode** [comment]
Correct usage
```php
'changed.from' => 'date:Y-m-d H:i:s',
```
