### ISSUE TITLE
Vertical bar in regex rule

### ISSUE THREAD

**Issue by Elmsellem** [rakit/validation#138]
Can't use vertical bar in regex rule
Example:
```php
$regex_rule = [ 'name' => 'regex:/(aaa|bbb)/'];
```
Result:
Fatal error: Uncaught Rakit\Validation\RuleNotFoundException: Validator 'bbb)/' is not registered

**Comment by dave-redfern** [comment]
@MohammedElmsellem you have to use the array syntax for complex regexes instead of the inline string. For example:
```
$regex_rule = [
    'name' => [
        'regex' => '/(aaa|bbb)/',
    ]
];
```

**Comment by Elmsellem** [comment]
@dave-redfern Another error occurred: Fatal error: Uncaught Rakit\Validation\RuleNotFoundException: Validator '/(aaa|bbb)/' is not registered.
I don't think it works like that, when you pass an array it take only values as list of rules.

**Comment by dave-redfern** [comment]
Ah! Whoopsie, my bad ☺️ Try instead:
```
[
    'name' => [
        'regex:/(aaa|bbb)/',
    ],
]
```

I just had to do this the other day myself. You need to have each rule as it's own array element though for that field, so watch out for that.

**Comment by Elmsellem** [comment]
@dave-redfern it works thanks 👍👍

**Comment by alaksandarjesus** [comment]
Here is my working example

tobh is time of birth in hours 

`
  "tobh" => [
                "required:true",
                "regex:/^([0-1]?[0-9]|2[0-3])$/"
            ],
`
