### ISSUE TITLE
Rules Registration/Modification

### ISSUE THREAD

**Issue by adelowo** [rakit/validation#14]
In the `readme` file, it says "Register/Modify Rule" but here( https://github.com/rakit/validation/blob/master/src/Validator.php#L109-#L113 ) it is explicitly set not to allow rule modification. 

The question is do you really want rule modification ? If yes, i should be able to send a PR.

**Comment by emsifa** [comment]
Yes.. maybe in some framework we want to modify existing rule adapting framework feature, we able to do it without using new rule name.

**Comment by adelowo** [comment]
Awesome then.. Would fix that
