### ISSUE TITLE
Custom Rule Callback

### ISSUE THREAD

**Issue by MarcusFulbright** [rakit/validation#21]
Is there a way to specify a custom function to use for validation? The use case I have in mind is validating foreign keys. This requires a DB lookup to see if the given value exists. Ideally, I would be able to supply a function that could do this.

**Comment by emsifa** [comment]
Currently there is no validation rule that accept callback/closure.

If you wanna add custom validation rule, you can follow [this instruction](https://github.com/rakit/validation#registermodify-rule).

**Comment by emsifa** [comment]
I think it is a good idea, so I've just added new callback rule at #22.

Now you can use something like this:

```php
$validation = $validator->validate($_POST, [
    'category_id' => [
        'required', 'numeric',
        function ($value) use ($pdo) {
            $result = $pdo->query("select count(*) as count from category where id = $value");
            return $result->fetch(PDO::FETCH_OBJ)->count > 0;
        }
    ]
]);
```
Here is the [documentation](https://github.com/rakit/validation#callback).
