### ISSUE TITLE
Regex rule - unexpected warning with comma character

### ISSUE THREAD

**Issue by Vandervir** [rakit/validation#23]
Hey hey,
I noticed some problem while using regex that contains comma.

when you have rule like this: `regex:/^([a-zA-Z\,]*)$/`
Final regex will be `/^([a-zA-Z\`

And that will result in following warning: `Warning: preg_match(): No ending delimiter '/' found  in ../rakit/validation/src/Rules/Regex.php on line 18`

That is main problem with parseRule method, that splits params no mater what.

instead:

> protected function parseRule($rule)
>    {
>        $exp = explode(':', $rule, 2);
        $rulename = $exp[0];
        $params = isset($exp[1])? explode(',', $exp[1]) : [];
        return [$rulename, $params];
    }

should be something like this:
>protected function parseRule($rule)
>    {
        $exp = explode(':', $rule, 2);
        $rulename = $exp[0];
        if ($rulename !== 'regex') {
            $params = isset($exp[1])? explode(',', $exp[1]) : [];
        } else {
            $params = [$exp[1]];
        }
        return [$rulename, $params];
    }

**Comment by emsifa** [comment]
Thanks for feedback. Yes, your solution is correct. Can you make PR for this?

**Comment by Vandervir** [comment]
I wanted to but I don't have permissions to push it

**Comment by adelowo** [comment]
@Vandevir fork this repository, then push to your forked version... Look at this https://gist.github.com/Chaser324/ce0505fbed06b947d962

https://help.github.com/articles/creating-a-pull-request/
https://help.github.com/articles/creating-a-pull-request-from-a-fork/
