### ISSUE TITLE
required_without is not working properly

### ISSUE THREAD

**Issue by orasik** [rakit/validation#26]
Hi,
I think there is a bug in `required_without`, it does not seem to work as expected. Please consider the following code:

```
use Rakit\Validation\Validator;

$validator = new Validator;
$data = [
    'name' => 'SomeName',
    'email' => 'someemail@somedomain',
    'surname' => 'Surname'
];

$validation = $validator->validate($data, [
    'name' => 'required_without:surname',
    'email' => 'required',
    'surname' => 'required_without:name'
]);

if($validation->fails()) {
    print_r($validation->errors());
} else {
    echo "Passed!";
}
```

My understanding is that if `surname` is presented then there should be an error.

What I want to achieve is that only `name` or `surname` should be presented in `$data`.

**Comment by emsifa** [comment]
Rules `required_*` only check that field must be present and not empty. So it would always be valid if you have non-empty value for that field.

For your case, we haven't rule for that. You can combine `required_without` with a custom rule like `not_present_with:key_a,key_b,key_c`.

It is not tested yet, I think it should be like this:

```php
use Rakit\Validation\Validator;
use Rakit\Validation\Rule;

class NotPresentWith extends Rule
{

    protected $message = "The :attribute is required";

    public function fillParameters(array $params)
    {
        $this->params['fields'] = $params;
        return $this;
    }

    public function check($value)
    {
        $this->requireParameters(['fields']);
        $fields = $this->parameter('fields');
        
        foreach ($fields as $field) {
            if ($this->validation->hasValue($field)) {
                $this->message = "The :attribute must not present with '{$field}'.";
                return false;
            }
        }

        return true;
    }

}

$validator = new Validator;
$validator->addValidator('not_present_with', new NotPresentWith);
```

Let me know if it works, I would add this rule in next release. Or you can make PR for it. :smiley:

**Comment by emsifa** [comment]
I close this for inactivity.

If anyone needs this rule, open it again. I will consider to add it.
