### ISSUE TITLE
Required If

### ISSUE THREAD

**Issue by callumb** [rakit/validation#31]
Is there away of having something like 

This elements needs to be set if the parent is set. So for example:

```php
[
    'order' => [
        0 => [
            "itemName" => 'shoe',
            "itemPrice" => '20.00',
            "quantity" => '1'
        ]
    ]
]
```

Basically want only to verify itemName, ItemPrice and quantity if order is set and is an array. 

I would make my own rule but best to see if its there first than to reinvent the wheel! :)

**Comment by callumb** [comment]
I see, So order.*.itemName won't be run unless order is true/ exists.

**Comment by emsifa** [comment]
Yes, and if you don't put `array` in `order` rules, and `order` value is string, rules in `order.*.itemName`, etc won't be running too.
