### ISSUE TITLE
Required if with array and checkboxes

### ISSUE THREAD

**Issue by ivansammartino** [rakit/validation#32]
Hello, and first thanks for this great package!
I have an array like this: 
```
[
    'products' => [
        '10' => [
            'quantity' => 8
            'has_notes' => 1
            'notes' => ''
        ],
        '12' => [
            'quantity' => 0
            'notes' => ''
        ],
        '14' => [
            'quantity' => 0
            'notes' => ''
        ],
    ]
]
```
Basically I'd like that, for each array item, the field `'notes'` is required if corresponding `'has_notes'` field  is present and it's 1 (it's a checkbox, so some items do not have this)

I tried with the following rule, but with no luck:
```
'products'         => 'array',
'products.*.notes' => 'required_if:products.*.has_notes,1',
```
Is there a way to do this or do I have to create a custom rule?
Thanks :-)

**Comment by emsifa** [comment]
Hello, thanks for your input.

This is a bug in `required_if` and some rules that needs other field value. It happens because those rules can't get value from their sibling.

I have just fixed this in #33, you can update to the latest version (it's in v0.17.0). Then use it like your code above.

**Comment by ivansammartino** [comment]
Thank you very much! :-)

**Comment by emsifa** [comment]
It should be solved. I will close this. Thank you again. :smiley:
