### ISSUE TITLE
How to set custom error message by per input not by error type

### ISSUE THREAD

**Issue by sudhir600** [rakit/validation#39]
Hi team,

Your work is really great but may you guide me that, is it possible or not to set error message like this. 
```
$validation_a = $validator->validate($dataset_a, $rules_for_dataset_a, [
	'["inputName"]required' => 'custom message for required but only for that input',
        '["inputName"]string' => 'only string allowed',
        '["inputName"]max=10' => 'string len should be maximum 10',
	'email' => ':email tidak valid',
	// etc
]);
```

See now these day requirement is very vast.  you can not set generic required message for all 100 field. Let's say I have very very long form and most of the field need to be required but the required message also should be very customized. 
Consider this scenario. 
you have name [string ]field and your zone [number].
Here requirement is that both are the mandatory field but if zone have no value then you need to enter 0 for skip. So here what i will error show that, 
"Zone id is missing, Please enter 0 if you don't have zone id".

**Comment by emsifa** [comment]
For that case you can do this instead:

```php
$validation_a = $validator->validate($dataset_a, $rules_for_dataset_a, [
	'inputName:required' => 'custom message for required but only for that input',
        'inputName:string' => 'only string allowed',
        'inputName:max' => 'string len should be maximum 10',
	'email' => ':email tidak valid',
	// etc
]);
```

**Comment by sudhir600** [comment]
Ohh its possible there.. Thanks @emsifa 
I will try this.
