### ISSUE TITLE
Require field when either of two fields are present

### ISSUE THREAD

**Issue by jdhollander** [rakit/validation#40]
I have a use case where I have two checkbox fields, either of which when checked requires an email address field to be populated.

```php
$validation = $validator->validate($_POST, [
  'email' => [
    'required_with:emailme',
    'required_with:newsletter',
    'email'
  ],
  'emailme' => '',
  'newsletter' => ''
]);
```
```php
$validation = $validator->validate($_POST, [
  'email' => 'required_with:emailme|required_with:newsletter|email',
  'emailme' => '',
  'newsletter' => ''
]);
```

Neither of these above examples work correctly. When the emailme checkbox is 'on' and the newsletter checkbox isn't, it doesn't require the email like I think it should. Other combinations are ok, so it appears that the first required_with is getting ignored.

Is it not possible to use required_with more than once for a field?

**Comment by emsifa** [comment]
You can separate another fields using `,` in `required_with` parameter like this:

```php
$validation = $validator->validate($_POST, [
  'email' => 'required_with:emailme,newsletter|email'
]);
```
It would make `email` required if **one of those** field is **present** in `$_POST` data:

**Comment by jdhollander** [comment]
I've just reread the documentation and I can't believe I missed that.

Thanks for getting back to me so quickly, it's really appreciated.
