### ISSUE TITLE
How to get detailed error response

### ISSUE THREAD

**Issue by prashant-saxena** [rakit/validation#55]
Hi,

First of all, I really appreciate your work on rakit/validaiton.
I was trying my hands on with this lib, but not able to figure out.
When I'm printing

`json_encode($errors->firstOfAll())`

I'm getting
`["The Email is not valid email","The Password minimum is 10"]`

Here we have no way relate these messages to which data member and further error is related to which rule. Is it possible to get some thing like this:

`email : ['require': 'email is required', 'email:'not a valid email']`

It would be really helpful.

Cheers
Prashant

**Comment by emsifa** [comment]
You can use `$errors->toArray()` to get all error messages. It will return something like this:

```php
[
  'email' => ['email' => '...', 'lowercase' => '...'],
  'password' => ['min' => '...', 'regex' => '...'],
   ...
]
```

Just a note, `required_*` rules is implicit rule, that means if it's not valid, other rules will be ignored. So you will only get 1 error message for that field.
