### ISSUE TITLE
validate only if data array is equal to rule array

### ISSUE THREAD

**Issue by tdias25** [rakit/validation#56]
theres is some rule/option to validate only if the data array are equal to the predefined rules index?

imagine this situation, this is a registration form, and validates the POST data:

```
$validation_rules = array(
		'name' => 'required'
	);	

	$_POST['name'] = 'John Doe';

	$validator = new Validator();

		$validation = $validator->make($_POST, $validation_rules);
		$validation->validate();

		if(!$validation->fails()) {
			//OK 
         //create user
		}
```

if the user sends some random field, like:

$_POST['cash'] = 9999;

the validation still passes and, if theres a field called "cash", it sets to 999, theres some option to `$validation->lockEquals();`?

**Comment by emsifa** [comment]
There is no API to do something like that. If you want prevent "cash" to sets, you can get validated values only using `$valuesToInsertOrUpdate = $validation->getValidatedData()`.

Here is the [detail](https://github.com/rakit/validation#getting-validated-valid-and-invalid-data).
