### ISSUE TITLE
getValidData() returns new elements when using dot notation

### ISSUE THREAD

**Issue by henninghorn** [rakit/validation#58]
I've noticed that the getValidData() returns new elements when using the dot-notation.

This is a snippet of my data
```php
$data['logoImagePaths'] = [
    '1x' => 'http://example.com/1x.png',
    '2x' => 'http://example.com/2x.png',
];
```

Part of my rules:
```
'logoImagePaths'    => 'required|array',
'logoImagePaths.1x' => 'required|url',
'logoImagePaths.2x' => 'required|url',
```

And this is that getValidData returns:
```php
print_r($validation->getValidData());
```
```
[logoImagePaths] => Array
(
    [1x] => http://example.com/1x.png
    [2x] => http://example.com/2x.png
 )

[logoImagePaths.1x] => http://example.com/1x.png
[logoImagePaths.2x] => http://example.com/2x.png
```

Is this expected? Or is it a bug?

**Comment by emsifa** [comment]
No, it shouldn't return those elements. I think I'm missing something in `setValidData` and `setInvalidData` in `Validation` class. I will check it later after my vacation. PR are welcome.
