### ISSUE TITLE
Not possible to validate incoming json array

### ISSUE THREAD

**Issue by roquie** [rakit/validation#60]
Case:
In the incoming request application receives the json array like this:
```json
["5662", "4c56ea8b-024f-3208-8f35-f998cc620f7e", 1, null]
```

It should be validated. How example, any of array value must be `integer`. But if u use `*` star match criteria, validating library will skip this input.

How to reproduce?
```php
$body = ["5662", "4c56ea8b-024f-3208-8f35-f998cc620f7e", 1, null];
$validation = $validator->validate($body, [
    '*'  => 'required|integer',
]);

if ($validation->fails()) {
   // no.
}
```

I think `*` star criteria functionality must be extended for such cases.

What do you think about it?

**Comment by emsifa** [comment]
Sorry for slow response.

In case like that, normally we can put `$body` into array assoc like this:

```php
$validation = $validator->validate(['body' => $body], [
    // 'body' => 'required|array', // in case you want body cannot be empty/null
    'body.*' => 'required|integer',
]);
```

**Comment by roquie** [comment]
Maybe I create a PR with intuitive behavior (like my example)?

**Comment by emsifa** [comment]
Sure, let me see. I will check it.

**Comment by emsifa** [comment]
I should close this for inactivity. Open again if you have an idea to do this, or just create PR directly. Thanks.
