### ISSUE TITLE
Regex rule breaks when the regex contains pipe character(s)

### ISSUE THREAD

**Issue by thomasfw** [rakit/validation#78]
A regex rule containing the pipe (`|`) character such as...

`url|regex:/^.*\.(jpg|JPG|gif|GIF|doc|DOC|pdf|PDF)$/`

... breaks the Regex validator:

```
Fatal error: Uncaught Rakit\Validation\RuleNotFoundException: Validator 'JPG' is not registered in ..vendor/rakit/validation/src/Validator.php on line 103
```

---

I'm trying to validate the extension based on an existing file's url. It would be nice if there was a built in validator similar to `mime` to achieve this for when we're handling file urls/paths in the input rather than as a $_FILES upload. Although the regex would suffice if this can be fixed!

Awesome library by the way :)

**Comment by emsifa** [comment]
Hi, thanks  @thomasfw

Yes, that's the limitation with regex rule. In case you need pipe character in regex rule, you should define rules using array like:

```php
$validation = $validator->validate($inputs, [
    'something' => ['required', $validator('regex', "/\.(png|jpg|pdf)$/")]
]);
```

Yeah, I think we need a rule to check path or url validity. I will try to make it during my free time. If you have an idea to do that, feel free to create a PR :)

**Comment by thomasfw** [comment]
I've made a PR for an `extension` rule, let me know if you want me to make any changes. Maybe `file_extension` would be a more fitting rule name?

**Comment by emsifa** [comment]
Sorry for late response, I'm so busy this week.

I think it is fine with `extension` name.

I will add this in new release. Thanks.

**Comment by circletime** [comment]
@emsifa This array solution is a great solution. Would be extremely helpful if it was stated explicitly in the documentation as a feature. Right now, this issue presents itself as a bug, since it takes a very very long time to find this solution. (In fact, I switched to this tool, because the previous tool had the same pipe issue.)
