### ISSUE TITLE
please man, give an option to make :attribute starting with lower case

### ISSUE THREAD

**Issue by Jossnaz** [rakit/validation#83]
:attribute is not the actual attribute value, please man, why not?

why make it start with capital letter?

e.g. attribute name is

'nextPayDate'

you return 'NextPayDate' man why... please man

**Comment by emsifa** [comment]
We capitalize attribute name because mostly we give input name same as it's label, and we usually use label that starts with capital letter.

I you want to use original key, you can use:

```php
$validator = new Validator;
$validator->setUseHumanizedKeys(false);
```

**Comment by Jossnaz** [comment]
you guys are the best!
