### ISSUE TITLE
Validating min/max numbers

### ISSUE THREAD

**Issue by arnaslu** [rakit/validation#85]
I'm trying to validate input number from GET parameter with this rule - `integer|min:1|max:100`. The value itself is a string `'200'` since it's coming from `$_GET`. In this case all rules pass, but I was hoping `max:100` would fail. Do you have a suggestion how to force min/max rules to treat value as a number?

**Comment by bsoliveira** [comment]
validation/src/Rules/Traits/SizeTrait.php->getValueSize($value)

    protected function getValueSize($value)
    {                      
        if (is_numeric($value) || is_float($value)) {
            return (float) $value;
        } 
        ...
    }

**Comment by kidstell** [comment]
i think its counter intuitive but the solution lies in using the numeric validator
```numeric|min:100|max:200```
if you use the integer validator, the min/max rules are almost ignored.

**Comment by sefirosweb** [comment]
Hi guys for me seems is not working i have numeric / interger with min max and seems is ignoring

![image](https://user-images.githubusercontent.com/20754836/128850615-a16db36c-da47-434a-9b4d-bc697cacd207.png)
