### ISSUE TITLE
String type number use min rules error

### ISSUE THREAD

**Issue by lizhichao** [rakit/validation#89]
in SizeTrait.php
在用min验证规则时候出现错误。
从表单获取的值数字是字符串类型的，仅仅通过 is_int($value) || is_float($value) 来判断不正确。
希望加上 is_int($value) || is_float($value) || is_numeric($value)

**Comment by naquad** [comment]
Stumbled upon the same problem. I think it would make sense if integer and numeric would cast checked value to number.
