### ISSUE TITLE
Pass value to error message

### ISSUE THREAD

**Issue by tukataka** [rakit/validation#95]
Hello!
As a developer I would like to use attribute value in error message. On my opinion it's very usable for forms validation.

**Comment by jakewhiteley** [comment]
@tukataka When defining an error message, you can use `:value` as a placeholder to get the attribute value:

````php
$validator = new Validator;

$validation_a = $validator->make($dataset_a, [
	'age' => 'required|min:18'
]);

$validation_a->setMessages([
	'age:min' => ':value is too young. 18+ only',
]);

$validation_a->validate();
````

**Comment by tukataka** [comment]
Sorry, I haven't founded this information in vendor dir (I don't know why). So, I decided that it's not possible.
Thank you!
