### ISSUE TITLE
How to make a multiple file input required?

### ISSUE THREAD

**Issue by IgorNoskov** [rakit/validation#97]
I have input:
`<input type="file" name="document[]">`

I made validation:
`'document.*' => 'required|uploaded_file:0,10M,pdf,jpeg,jpg',`

But, its did't work. An empty field is validated. Please, help me.

**Comment by emsifa** [comment]
What do you mean by "an empty field is validated"? do you want to make it optional? or in your case it is valid where it shouldn't be valid?

**Comment by IgorNoskov** [comment]
The field is sent with null value on a form submit and it passes validation, although the 'required' flag is used.

> What do you mean by "an empty field is validated"? do you want to make it optional? or in your case it is valid where it shouldn't be valid?

The field is sent with null value on a form submit and it passes validation, although the 'required' flag is used.

**Comment by emsifa** [comment]
Can you show your validation code and `print_r($_FILES)` result?

**Comment by IgorNoskov** [comment]
Thank you, Muhammad Syifa! In fact I created custom rule - FileRule. This is a wrapper over the Rakit\Validation\Rules\UploadedFile class. Here code:
```php
<?php

namespace App;

use Rakit\Validation\Rules\UploadedFile;
/**
 * Class FileRule.
 *
 * Need to make a dummy object when passing tests on PHPUnit.
 *
 * @package App
 */
class FileRule extends UploadedFile
{
}
```

I created it for tests purpose.

I tried this rule `'document.*' => 'required|uploaded_file:0,10M,png,jpeg'` and its work. But when I use this code: `'document.*' => 'required|file:0,10M,png,jpeg'` its not work. 
Here code:
```php
/**
     * Validates values.
     *
     * @return void
     * @throws \Rakit\Validation\RuleQuashException
     */
    private function validate()
    {
        $validator = new Validator([
            'required'    => ':attribute - обязательное поле.',
            'file'        => ':attribute - тип файла и размер должны соответствовать требованиям',
        ]);

        $validator->addValidator('file', $this->file_rule);

        $validation = $validator->make([
            'document' => $this->document,
        ], [
            'document.*' => 'required|file:0,10M,png,jpeg',
        ]);

        $validation->setAliases([
            'document' => 'СНИЛС',
        ]);

        $validation->validate();

        if ($validation->fails()) {
            $this->errors = $validation->errors()->all();
        }
    }
```

**Comment by emsifa** [comment]
Ah, that is because we have special treatment for `uploaded_file` in `required` rule. 

[https://github.com/rakit/validation/blob/82e354c144665b66f5fe1d75435ac3d996b09c77/src/Rules/Required.php#L27-L29](https://github.com/rakit/validation/blob/82e354c144665b66f5fe1d75435ac3d996b09c77/src/Rules/Required.php#L27-L29)

So for now it is not possible to extend `UploadedFile` rule with different rule name.

**Comment by IgorNoskov** [comment]
Thank you! I will try to solve the problem differently.
